# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 22:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Criterios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('carga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataentrega', models.DateField()),
                ('informacoes', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
                ('previsaoentrega', models.DateField()),
                ('especificacao', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nomeprojeto', models.CharField(max_length=500)),
                ('descricao', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=500)),
                ('descricao', models.CharField(max_length=2000)),
                ('especificacao', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PI.Pessoa')),
            ],
            bases=('PI.pessoa',),
        ),
        migrations.CreateModel(
            name='Apresentacao',
            fields=[
                ('etapas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PI.Etapas')),
            ],
            bases=('PI.etapas',),
        ),
        migrations.CreateModel(
            name='AvaliacaoAluno',
            fields=[
                ('avaliacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PI.Avaliacao')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PI.Aluno')),
            ],
            bases=('PI.avaliacao',),
        ),
        migrations.CreateModel(
            name='AvaliacaoGrupo',
            fields=[
                ('avaliacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PI.Avaliacao')),
            ],
            bases=('PI.avaliacao',),
        ),
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PI.Pessoa')),
            ],
            bases=('PI.pessoa',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PI.Pessoa')),
            ],
            bases=('PI.pessoa',),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PI.Projeto'),
        ),
        migrations.AddField(
            model_name='etapas',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PI.Projeto'),
        ),
        migrations.AddField(
            model_name='entregas',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PI.Etapas'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PI.Etapas'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PI.Professor'),
        ),
        migrations.AddField(
            model_name='entregas',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PI.Aluno'),
        ),
        migrations.AddField(
            model_name='criterios',
            name='apresentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PI.Apresentacao'),
        ),
        migrations.AddField(
            model_name='avaliacaogrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PI.Grupo'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PI.Avaliador'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PI.Grupo'),
        ),
    ]
