# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PI', '0002_auto_20171003_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
